// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"gopkg.in/guregu/null.v4/zero"
)

type Otp struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Status    string    `json:"status"`
	Code      string    `json:"code"`
	ExpiresAt zero.Time `json:"expires_at"`
	CreatedAt zero.Time `json:"created_at"`
}

type Role struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	Name      string      `json:"name"`
	CreatedAt zero.Time   `json:"created_at"`
	CreatedBy zero.String `json:"created_by"`
}

type Sysuser struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	Name      string      `json:"name"`
	Phone     string      `json:"phone"`
	Password  string      `json:"password"`
	CreatedAt zero.Time   `json:"created_at"`
	CreatedBy zero.String `json:"created_by"`
}

type SysuserRole struct {
	ID        string `json:"id"`
	SysuserID string `json:"sysuser_id"`
	RoleID    string `json:"role_id"`
}

type User struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	CreatedAt zero.Time   `json:"created_at"`
	CreatedBy zero.String `json:"created_by"`
}
