// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: otp.sql

package sqlc

import (
	"context"

	"gopkg.in/guregu/null.v4/zero"
)

const getOTPByID = `-- name: GetOTPByID :one
SELECT id, email, code, status, expires_at
FROM otp
WHERE id = $1::uuid AND status = $2
`

type GetOTPByIDParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

type GetOTPByIDRow struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	Status    string    `json:"status"`
	ExpiresAt zero.Time `json:"expires_at"`
}

func (q *Queries) GetOTPByID(ctx context.Context, arg GetOTPByIDParams) (GetOTPByIDRow, error) {
	row := q.db.QueryRow(ctx, getOTPByID, arg.ID, arg.Status)
	var i GetOTPByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const insertOTP = `-- name: InsertOTP :one
INSERT INTO otp (
    id,
    email,
    code,
    status,
    expires_at
) VALUES (gen_random_uuid(), $1, $2, $3, $4) 
RETURNING id
`

type InsertOTPParams struct {
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	Status    string    `json:"status"`
	ExpiresAt zero.Time `json:"expires_at"`
}

func (q *Queries) InsertOTP(ctx context.Context, arg InsertOTPParams) (string, error) {
	row := q.db.QueryRow(ctx, insertOTP,
		arg.Email,
		arg.Code,
		arg.Status,
		arg.ExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateOTPStatus = `-- name: UpdateOTPStatus :exec
UPDATE otp SET status = $1 WHERE id = $2::uuid
`

type UpdateOTPStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateOTPStatus(ctx context.Context, arg UpdateOTPStatusParams) error {
	_, err := q.db.Exec(ctx, updateOTPStatus, arg.Status, arg.ID)
	return err
}
