// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateSysRoles(ctx context.Context, arg CreateSysRolesParams) error
	CreateSysuser(ctx context.Context, arg CreateSysuserParams) (string, error)
	GetOTPByID(ctx context.Context, arg GetOTPByIDParams) (GetOTPByIDRow, error)
	GetRoleById(ctx context.Context, arg GetRoleByIdParams) (GetRoleByIdRow, error)
	GetSysuserByPhone(ctx context.Context, arg GetSysuserByPhoneParams) ([]Sysuser, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	InsertOTP(ctx context.Context, arg InsertOTPParams) (string, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
	RoleList(ctx context.Context, status string) ([]RoleListRow, error)
	UpdateOTPStatus(ctx context.Context, arg UpdateOTPStatusParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
}

var _ Querier = (*Queries)(nil)
