// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateSysRoles(ctx context.Context, arg CreateSysRolesParams) error
	RoleList(ctx context.Context, status string) ([]RoleListRow, error)
	SelectSysUsers(ctx context.Context, arg SelectSysUsersParams) ([]Sysuser, error)
	SysUsers(ctx context.Context, arg SysUsersParams) (string, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
}

var _ Querier = (*Queries)(nil)
