// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package sqlc

import (
	"context"

	"gopkg.in/guregu/null.v4/zero"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles(name, status) VALUES ($1,$2)
`

type CreateRoleParams struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole, arg.Name, arg.Status)
	return err
}

const createSysRoles = `-- name: CreateSysRoles :exec
INSERT INTO sysuser_roles(id,sysuser_id,role_id) VALUES ($1,$2,$3)
`

type CreateSysRolesParams struct {
	ID        string `json:"id"`
	SysuserID string `json:"sysuser_id"`
	RoleID    string `json:"role_id"`
}

func (q *Queries) CreateSysRoles(ctx context.Context, arg CreateSysRolesParams) error {
	_, err := q.db.Exec(ctx, createSysRoles, arg.ID, arg.SysuserID, arg.RoleID)
	return err
}

const roleList = `-- name: RoleList :many
SELECT 
    id,
    name,
    created_at
    FROM roles WHERE status=$1
`

type RoleListRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt zero.Time `json:"created_at"`
}

func (q *Queries) RoleList(ctx context.Context, status string) ([]RoleListRow, error) {
	rows, err := q.db.Query(ctx, roleList, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleListRow
	for rows.Next() {
		var i RoleListRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles SET name=$1  WHERE id = $2
`

type UpdateRoleParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.Name, arg.ID)
	return err
}
