// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sysuser.sql

package sqlc

import (
	"context"

	"gopkg.in/guregu/null.v4/zero"
)

const selectSysUsers = `-- name: SelectSysUsers :many
SELECT
    id, status, name, phone, password, created_at, created_by
    FROM sysusers WHERE status = $1 AND phone=$2
`

type SelectSysUsersParams struct {
	Status string `json:"status"`
	Phone  string `json:"phone"`
}

func (q *Queries) SelectSysUsers(ctx context.Context, arg SelectSysUsersParams) ([]Sysuser, error) {
	rows, err := q.db.Query(ctx, selectSysUsers, arg.Status, arg.Phone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sysuser
	for rows.Next() {
		var i Sysuser
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Phone,
			&i.Password,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sysUsers = `-- name: SysUsers :one
INSERT INTO sysusers (
    id,
    status,
    name,
    phone,
    password,
    created_at,
    created_by
    ) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id
`

type SysUsersParams struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	Name      string      `json:"name"`
	Phone     string      `json:"phone"`
	Password  string      `json:"password"`
	CreatedAt zero.Time   `json:"created_at"`
	CreatedBy zero.String `json:"created_by"`
}

func (q *Queries) SysUsers(ctx context.Context, arg SysUsersParams) (string, error) {
	row := q.db.QueryRow(ctx, sysUsers,
		arg.ID,
		arg.Status,
		arg.Name,
		arg.Phone,
		arg.Password,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
