// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sysuser.sql

package sqlc

import (
	"context"

	"gopkg.in/guregu/null.v4/zero"
)

const createSysuser = `-- name: CreateSysuser :one
INSERT INTO sysusers (
    id,
    status,
    name,
    phone,
    password,
    created_at,
    created_by
    ) VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,$6) RETURNING id
`

type CreateSysuserParams struct {
	Status    string      `json:"status"`
	Name      string      `json:"name"`
	Phone     string      `json:"phone"`
	Password  string      `json:"password"`
	CreatedAt zero.Time   `json:"created_at"`
	CreatedBy zero.String `json:"created_by"`
}

func (q *Queries) CreateSysuser(ctx context.Context, arg CreateSysuserParams) (string, error) {
	row := q.db.QueryRow(ctx, createSysuser,
		arg.Status,
		arg.Name,
		arg.Phone,
		arg.Password,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSysuserByPhone = `-- name: GetSysuserByPhone :many
SELECT
    id, status, name, phone, password, created_at, created_by
    FROM sysusers WHERE status = $1 AND phone=$2
`

type GetSysuserByPhoneParams struct {
	Status string `json:"status"`
	Phone  string `json:"phone"`
}

func (q *Queries) GetSysuserByPhone(ctx context.Context, arg GetSysuserByPhoneParams) ([]Sysuser, error) {
	rows, err := q.db.Query(ctx, getSysuserByPhone, arg.Status, arg.Phone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sysuser
	for rows.Next() {
		var i Sysuser
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Phone,
			&i.Password,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
