// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"

	"gopkg.in/guregu/null.v4/zero"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password, status, created_at
FROM users
WHERE email = $1 AND status = $2
`

type GetUserByEmailParams struct {
	Email  string `json:"email"`
	Status string `json:"status"`
}

type GetUserByEmailRow struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Password  string    `json:"password"`
	Status    string    `json:"status"`
	CreatedAt zero.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.Status)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
    email,
    name,
    password,
    status
) VALUES ($1, $2, $3, $4)
`

type InsertUserParams struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Status   string `json:"status"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Status,
	)
	return err
}
